export const events = [
  {
    name: "Weddings",
    slug: "weddings",
    images: [
      "/media/weddings-1.jpg",
      "/media/weddings-2.jpg",
      "/media/weddings-3.jpg",
      "/media/weddings-4.jpg",
      "/media/weddings-5.jpg",
      "/media/weddings-6.jpg",
      "/media/weddings-7.jpg",
      "/media/weddings-8.jpg",
      "/media/weddings-9.jpg",
      "/media/weddings-10.jpg",
    ],
  },
  {
    name: "Corporate Events",
    slug: "corporate-events",
    images: [
      "/media/corporate-1.jpg",
      "/media/corporate-2.jpg",
      "/media/corporate-3.jpg",
      "/media/corporate-4.jpg",
      "/media/corporate-5.jpg",
    ],
  },
  {
    name: "Birthday Celebrations",
    slug: "birthday-celebrations",
    images: [
      "/media/birthday-1.jpg",
      "/media/birthday-2.jpg",
      "/media/birthday-3.jpg",
      "/media/birthday-4.jpg",
      "/media/birthday-5.jpg",
      "/media/birthday-6.jpg",
      "/media/birthday-7.jpg",
      "/media/birthday-8.jpg",
      "/media/birthday-9.jpg",
      "/media/birthday-10.jpg",
    ],
  },
  {
    name: "Anniversaries",
    slug: "anniversaries",
    images: [
      "/media/anniversaries-1.jpg",
      "/media/anniversaries-2.jpg",
      "/media/anniversaries-3.jpg",
      "/media/anniversaries-4.jpg",
      "/media/anniversaries-5.jpg",
    ],
  },
  {
    name: "Engagements",
    slug: "engagements",
    images: [
      "/media/engagements-1.jpg",
      "/media/engagements-2.jpg",
      "/media/engagements-3.jpg",
      "/media/engagements-4.jpg",
      "/media/engagements-5.jpg",
      "/media/engagements-6.jpg",
      "/media/engagements-7.jpg",
      "/media/engagements-8.jpg",
      "/media/engagements-9.jpg",
      "/media/engagements-10.jpg",
    ],
  },
  {
    name: "Conferences",
    slug: "conferences",
    images: [
      "/media/conferences-1.jpg",
      "/media/conferences-2.jpg",
      "/media/conferences-3.jpg",
      "/media/conferences-4.jpg",
      "/media/conferences-5.jpg",
    ],
  },
  {
    name: "Festivals",
    slug: "festivals",
    images: [
      "/media/festivals-1.jpg",
      "/media/festivals-2.jpg",
      "/media/festivals-3.jpg",
      "/media/festivals-4.jpg",
      "/media/festivals-5.jpg",
      "/media/festivals-6.jpg",
      "/media/festivals-7.jpg",
      "/media/festivals-8.jpg",
      "/media/festivals-9.jpg",
      "/media/festivals-10.jpg",
    ],
  },
  {
    name: "Concerts & Performances",
    slug: "concerts-performances",
    images: [
      "/media/concerts-1.jpg",
      "/media/concerts-2.jpg",
      "/media/concerts-3.jpg",
      "/media/concerts-4.jpg",
      "/media/concerts-5.jpg",
    ],
  },
  {
    name: "Receptions",
    slug: "receptions",
    images: [
      "/media/receptions-1.jpg",
      "/media/receptions-2.jpg",
      "/media/receptions-3.jpg",
      "/media/receptions-4.jpg",
      "/media/receptions-5.jpg",
      "/media/receptions-6.jpg",
      "/media/receptions-7.jpg",
      "/media/receptions-8.jpg",
      "/media/receptions-9.jpg",
      "/media/receptions-10.jpg",
    ],
  },
]
